"""empty message

Revision ID: 4bdedcf1ea0a
Revises: 583ba435e4dd
Create Date: 2017-09-14 04:46:33.196161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bdedcf1ea0a'
down_revision = '583ba435e4dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'items', 'sources', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.drop_column('items', 'owner_id')
    # ### end Alembic commands ###
