"""empty message

Revision ID: 654108f85881
Revises: 4bdedcf1ea0a
Create Date: 2017-09-14 04:49:41.512989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '654108f85881'
down_revision = '4bdedcf1ea0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('items_owner_id_fkey', 'items', type_='foreignkey')
    op.create_foreign_key(None, 'items', 'users', ['user_id'], ['id'])
    op.drop_column('items', 'owner_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.create_foreign_key('items_owner_id_fkey', 'items', 'sources', ['owner_id'], ['id'])
    op.drop_column('items', 'user_id')
    # ### end Alembic commands ###
